name: Deploy NGINX to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.EC2_HOST }}
      USERNAME: ${{ secrets.EC2_USER }}
      SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      TARGET_DIR: "~/cicd"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_KEY }}
          source: "./"
          target: ${{ env.TARGET_DIR }}

      - name: Run setup script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_KEY }}
          script: |
            sudo chmod +x ~/cicd/setup.sh && sudo ~/cicd/setup.sh
